app = "reminder-calendar"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_ENV = "production"
  DB_HOST = "reminder-db.internal"
  DB_PORT = "3306"
  DB_DATABASE = "reminder"
  DB_USERNAME = "reminder"
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
