app = 'reminder-mysql-db'
primary_region = 'fra'

[build]

[env]
  MYSQL_DATABASE = "reminder"
  MYSQL_USER = "reminderuser"
  MYSQL_PASSWORD = "secretpassword"
  MYSQL_ROOT_PASSWORD = "rootpass"

[[mounts]]
  source = 'mysql_data'
  destination = '/var/lib/mysql'

[[services]]
  internal_port = 3306
  protocol = "tcp"

  [[services.ports]]
    port = 3306

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
